### ISSUE TITLE
Stuck in Session Expired state in force_auth

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3283]
## STR 

1. Create a new Firefox Profile
1. Sign in to sync ( about:accounts?entryPoint=menupanel ) 
1. Create an account and verify
1. Click manage in about prefs: 
![image](https://cloud.githubusercontent.com/assets/128755/11133396/a704f170-8963-11e5-86b3-c26c4d6e88fc.png)
1. Delete firefox account:
![image](https://cloud.githubusercontent.com/assets/128755/11133405/b482395c-8963-11e5-9647-3a1bcc46a60f.png)
1. Open https://accounts.firefox.com/signup , create account with the same email, verify.
1. Open about:preferences#sync click "Manage"
1. Try to force auth login

## Expected

Should sign in

## Actual

![zxasd](https://cloud.githubusercontent.com/assets/128755/11133533/4e10473a-8964-11e5-92de-b5beaf79316c.gif)

Stuck in "Session Expired"

cc @philbooth @shane-tomlinson

**Comment by vladikoff** [comment]
I had other issues getting stuck in this "session expired" state but this is the only way so far I was able to reproduce it 100%

**Comment by vladikoff** [comment]
I made a dashboard to see how many session expired we actually get: https://app.datadoghq.com/dash/80495

**Comment by vladikoff** [comment]
Could be related to : https://github.com/mozilla/fxa-content-server/issues/1964 but it was fixed

**Comment by vladikoff** [comment]
from mtg: one easy, if users see "Session Expired" we could clear local storage and cookies. 
    (we might tell the browser that user was cleared)

**Comment by shane-tomlinson** [comment]
@vladikoff - I am unable to reproduce locally with the steps outlined. 

The original problem occurred because the browser was incorrectly notified that the account was deleted/signed out, we were not sending a uid.

The notification/behavior was fixed by [this change in the multi-device PR](https://github.com/mozilla/fxa-content-server/pull/3274/files#diff-f6f26d253984759fd1ff90518fbcde33R162). The browser correctly listened for the `fxaccounts:logout` and `fxaccounts:delete` [WebChannel command](https://dxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccountsWebChannel.jsm#154), and expected a `uid`. We were not sending the `uid`, so the browser [ignored the command](https://dxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccountsWebChannel.jsm#263). Now that we send the `uid`, all works as expected.

@vladikoff - can you confirm this is fixed and close if so?

**Comment by shane-tomlinson** [comment]
Another though, this will probably still be a problem if the user deletes the account from a 2nd browser/device.

**Comment by shane-tomlinson** [comment]
> Another thought, this will probably still be a problem if the user deletes the account from a 2nd browser/device.

This is still a problem with the following STRs:

1. In browser A, sign up for Sync, verify, close FxA.
1. In browser B, sign in as same user, delete account.
1. In browser B
1. In browser A, open `about:preferences#sync`, click `Manage Account`, try to sign in. `Session expired`, the URL query params disappear after the fist submit, the error message goes away quickly.

![manage-account-session-expired](https://cloud.githubusercontent.com/assets/848085/11651939/7d32dbea-9d8c-11e5-8ef0-26d4cf887037.gif)

**Comment by shane-tomlinson** [comment]
The case outlined above is potentially more difficult to handle, force_auth will have been loaded up with an old uid and valid email address. The user should be able to sign in, and the browser notified of the new uid. I'm not sure whether the browser will update its state accordingly, the `login` message will be sent with the new uid, [the onLogin method](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/aboutaccounts/aboutaccounts.js#200) should be invoked from the browser's aboutaccounts.js file, and the new account data should [be set on the fxAccounts model](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/aboutaccounts/aboutaccounts.js#238). Seems like it should work, as long as we allow the user to sign in with the new uid/existing email.

**Comment by shane-tomlinson** [comment]
There are multiple problems:

1. Firefox loads the `/settings` page without either `context` or `service`. The default settings.uri is:
`https://accounts.firefox.com/settings`. If the user is kicked to `force_auth` from `settings` because their session is no longer valid, the `BaseAuthenticationBroker` will be used, not `FxDesktopV1` or `FxDesktopV2`. No `login` message will be sent even if the user were able to authenticate with FxA.
1. Firefox loads the `/settings` page with a `uid` query parameter, which is entirely ignored by the `force_auth` page. `force_auth` only cares about `email`. An `Account` model [is created](https://github.com/mozilla/fxa-content-server/blob/4163505c0266ec472cf75a58042212aa5f2fee03/app/scripts/views/force_auth.js#L69) with the relier set email and user entered password. In [onSigninSuccess](https://github.com/mozilla/fxa-content-server/blob/4163505c0266ec472cf75a58042212aa5f2fee03/app/scripts/views/force_auth.js#L89), the current `uid` is not compared against the relier set `uid`, and the relier model still contains the old `uid`. When the user is redirected to the `/settings` page the `settings-mixin` [sees the old relier-set `uid`](https://github.com/mozilla/fxa-content-server/blob/4163505c0266ec472cf75a58042212aa5f2fee03/app/scripts/views/mixins/settings-mixin.js#L19) and overwrites the newly signed in user. The [isUserAuthorized check in base.js](https://github.com/mozilla/fxa-content-server/blob/4163505c0266ec472cf75a58042212aa5f2fee03/app/scripts/views/base.js#L283) checks whether the old `uid` is authenticated, which it isn't, so the user is kicked back over to `force_auth`. Repeat.

**Comment by shane-tomlinson** [comment]
While we are digging in, should `isUserAuthorized` and `isUserVerified` be renamed to `isAccountAuthorized` and `isAccountVerified`? User and Account are two distinct concepts, both of these functions check Accounts, not Users.

**Comment by shane-tomlinson** [comment]
A bit more. The `Manage Account` link does not opens `/settings` in `about:accounts`, but rather its own tab. If we want the browser to handle a `login` notification with the new `uid`, the message must be sent via the FxDesktopV2 authentication broker which uses WebChannels or else the browser won't be listening for the message.

**Comment by shane-tomlinson** [comment]
Yet more!

With `identity.fxaccounts.settings.uri` set to `http://127.0.0.1:3030/settings?context=fx_desktop_v2&service=sync` and the following diff, re-signing in *seems* to work correctly:

```diff
diff --git a/app/scripts/views/force_auth.js b/app/scripts/views/force_auth.js
index dbee181..ac94d9e 100644
--- a/app/scripts/views/force_auth.js
+++ b/app/scripts/views/force_auth.js
@@ -86,6 +86,11 @@ define(function (require, exports, module) {
     onSignInSuccess: function (account) {
       var self = this;
       self.logViewEvent('success');
+
+      if (account.get('uid') !== self.relier.get('uid')) {
+        self.relier.set('uid', account.get('uid'));
+      }
+
       return self.invokeBrokerMethod('afterForceAuth', account)
         .then(function () {
           self.navigate(self._redirectTo || 'settings', {
```

Something about this feels off, perhaps the `uid` should be unset on the relier instead.

**Comment by shane-tomlinson** [comment]
ref #1856, #3040, #3062

**Comment by rfk** [comment]
Part of the problem here is that the browser doesn't detect that its sessionToken has been invalidated (by virtue of the whole account being deleted) so it still offers for you to manage the account, rather than forcing you to re-authenticate.  If web content sees that a session token is (a) invalid and (b) originally from sync signin, does it make sense to send an unsolicited webchannel "logout" message to the browser?  We *know* that browser's login state is busted, maybe we should tell it so.

**Comment by shane-tomlinson** [comment]
> does it make sense to send an unsolicited webchannel "logout" message to the browser? We know that browser's login state is busted, maybe we should tell it so.

We could and probably should, with the above patch the `logout` message is implied, and implicit anything eventually breaks. Hopefully sending a `logout` followed immediately by a `login` doesn't cause any timing issues.

**Comment by shane-tomlinson** [comment]
> We know that browser's login state is busted, maybe we should tell it so.

I had a quick chat with @philbooth about sending a `logout` and then a `login` message immediately afterwards. The `logout` message is processed asynchronously, sending a `login` before `logout` has completed could cause problems. We could update the browser to introduce a message queue. A message queue seems like it'd be a good defensive measure regardless, but this entire scenario is probably avoided with push notifications. I imagine all attached devices will be notified when an account is deleted.

Here is what I propose:

1. Add a small browser patch to update the default settings URI to include both a `context` and `service` query parameter, in the off chance a force_auth is needed.
1. Add the content server patch [from above](https://github.com/mozilla/fxa-content-server/issues/3283#issuecomment-162910089) in the off chance the UID is no good. We at least notify the browser of the new UID.
1. Defer everything else until after push notifications have landed and the [STRs that cause this problem](https://github.com/mozilla/fxa-content-server/issues/3283#issuecomment-162824153) are no longer possible.

**Comment by vladikoff** [comment]
> Defer everything else until after push notifications

After prototyping the push notifications in Orlando I noticed a few "showstoppers" for our push notification grand plan. We shall chat about those in https://github.com/mozilla/fxa-content-server/issues/3308#issuecomment-164833063

**Comment by vladikoff** [comment]
@shane-tomlinson bugzilla link? :D

**Comment by shane-tomlinson** [comment]
ref #3057

**Comment by shane-tomlinson** [comment]
ref #1964

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson bugzilla link? :D

https://bugzilla.mozilla.org/show_bug.cgi?id=1234165

**Comment by shane-tomlinson** [comment]
ref #3477

**Comment by vladikoff** [comment]
wait for email status patch
