### ISSUE TITLE
“Two-factor authentication enabled” notification is not localized

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#6728]
Hi,

I’ve been hitting this issue over the weekend while migrating 2FA to a new app, noticed the notification was not localized.

The string [is translated in French](https://pontoon.mozilla.org/fr/firefox-accounts/all-resources/?search=Two-step+authentication+enabled&string=177236), but appears in English.

The following screen is the “Recovery codes” screen, after setting up 2FA:
![image](https://user-images.githubusercontent.com/1294206/49018900-80949b80-f184-11e8-825b-1e9aae950746.png)

**Comment by shane-tomlinson** [comment]
I think this was probably due to the same reason as #6725, which fixed in #6726.

**Comment by TheoChevalier** [comment]
Killing two birds with one stone ;) Thanks Shane!

**Comment by shane-tomlinson** [comment]
Hmmm, the French translation is definitely there. I wonder if we'll have to test this on production.

**Comment by SorinaFlorean** [comment]
We will test then on production. @shane-tomlinson, if this is ok. Probably this applies also to https://github.com/mozilla/fxa-content-server/pull/6726.

**Comment by SorinaFlorean** [comment]
We tested this on production based on https://bugzilla.mozilla.org/show_bug.cgi?id=1510310#c16 and the issue is still reproducible. We changed the language of the device and also, the browser language with no effect. The notification is not translated.  @shane-tomlinson please tell me if we have to do something else in order to verify this.

**Comment by shane-tomlinson** [comment]
The strings were not correctly extracted for train-126. I'm going to have to ask for a re-check with train-127.

**Comment by shane-tomlinson** [comment]
This problem also applies to "New recovery codes generated"

<img width="494" alt="screenshot 2019-01-11 at 13 30 55" src="https://user-images.githubusercontent.com/848085/51036506-35541200-15a5-11e9-811b-faf52b427e54.png">

**Comment by TheoChevalier** [comment]
Also when you set up a recovery key and click “Print”, “Copy” or “Download”

<img width="405" alt="capture d ecran 2019-01-11 a 14 53 12" src="https://user-images.githubusercontent.com/1294206/51040990-c977a680-15b0-11e9-933a-f4db2a3c124e.png">
<img width="401" alt="capture d ecran 2019-01-11 a 14 53 23" src="https://user-images.githubusercontent.com/1294206/51040992-c977a680-15b0-11e9-908d-72b610ca932f.png">

**Comment by shane-tomlinson** [comment]
> Also when you set up a recovery key and click “Print”, “Copy” or “Download”

Well spotted, that's a slightly different bug. I'll get on that.
